
export const skills = [
    {
        name: 'React Native',
        percent: "75%",
        bgColor: 'green.400',
        iconName: 'react',
        iconColor: 'red.600',
    },

    {
        name: 'HTML5',
        percent: "90%",
        bgColor: 'green.400',
        iconName: 'language-html5',
        iconColor: 'red.600',
    },
    {
        name: 'CSS3',
        percent: "90%",
        bgColor: 'green.400',
        iconName: 'language-css3',
        iconColor: 'pink.600',
    },
    {
        name: 'javaScript',
        percent: "95%",
        bgColor: 'pink.400',
        iconName: 'language-javascript',
        iconColor: 'yellow.400',
    },
    {
        name: 'jQuery',
        percent: "80%",
        bgColor: 'pink.600',
        iconName: 'jquery',
        iconColor: 'blue.400',
    },
    {
        name: 'Ajax',
        percent: "99%",
        bgColor: 'green.400',
        iconName: 'alpha-a',
        iconColor: 'blue.600',
    },
    {
        name: 'React',
        percent: "95%",
        bgColor: 'green.400',
        iconName: 'react',
        iconColor: 'blue.400',
    },
    {
        name: 'Mongodb',
        percent: "80%",
        bgColor: 'pink.400',
        iconName: 'database',
        iconColor: 'blue.400',
    },
    {
        name: 'Node Js',
        percent: "95%",
        bgColor: 'green.400',
        iconName: 'nodejs',
        iconColor: 'blue.400',
    },
    {
        name: 'Express Js',
        percent: "95%",
        bgColor: 'green.400',
        iconName: 'nodejs',
        iconColor: 'blue.400',
    },
    {
        name: 'MySql',
        percent: "75%",
        bgColor: 'pink.400',
        iconName: 'database',
        iconColor: 'red.400',
    },

    {
        name: 'C & C++',
        percent: "70%",
        bgColor: 'red.400',
        iconName: 'language-cpp',
        iconColor: 'yellow.400',
    },
    {
        name: 'java',
        percent: "95%",
        bgColor: 'green.400',
        iconName: 'language-java',
        iconColor: 'blue.400',
    },
    {
        name: 'DSA Java',
        percent: "75%",
        bgColor: 'pink.400',
        iconName: 'language-javascript',
        iconColor: 'blue.400',
    },
    {
        name: 'Git',
        percent: "75%",
        bgColor: 'red.400',
        iconName: 'github',
        iconColor: 'yellow.400',
    },
];

